language: java
jdk: oraclejdk8

install: true
script: mvn clean install verify package compile test

travis env set DOCKER_USERNAME pruebagonzalourjc
travis env set DOCKER_PASSWORD aguilar

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag solucion-back pruebagonzalourjc/practica2
  - docker push pruebagonzalourjc/practica2
