language: java
jdk: oraclejdk8

install: true
script: mvn clean install verify package compile test sonar:sonar

env:
  - DOCKER_USERNAME=pruebagonzalourjc DOCKER_PASSWORD=aguilar

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key"
    token:
      secure: 8267438bd0c8bbc7204d6e1cefc7aee492824d72
    branches:
      - master
      - maintenance
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization={ORG_KEY} -Dsonar.login={GENERATED_KEY_ON_SONARCLOUD_SECURITY} -Dsonar.branch={BRANCH_NAME}
    
services:
  - docker

before_install:
  - docker build -t practicadocker .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag practicadocker pruebagonzalourjc/practica2
  - docker push pruebagonzalourjc/practica2
