language: java
jdk: oraclejdk8

install: true
script: mvn clean install verify package compile test

services:
  - docker

before_install:
  - docker login -u "pruebagonzalourjc" -p "aguilar"
  - docker tag solucion-back pruebagonzalourjc/practica2
  - docker push pruebagonzalourjc/practica2
