language: java
jdk: oraclejdk8

install: true
script: mvn clean install verify package compile test

env:
  - DOCKER_USERNAME=pruebagonzalourjc
  - DOCKER_PASSWORD=aguilar
    
    
services:
  - docker

before_install:
  - docker build -t practicaDocker .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag practicaDocker pruebagonzalourjc/practica2
  - docker push pruebagonzalourjc/practica2
