language: java
jdk: oraclejdk8

install: true
script: mvn clean install verify package compile test

env:
  global:
    # travis encrypt DOCKER_PASSWORD=aguilar
    # travis encrypt DOCKER_USERNAME=pruebagonzalourjc
    
    
services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag solucion-back pruebagonzalourjc/practica2
  - docker push pruebagonzalourjc/practica2
