server:
  port: 8081
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create 
  
management:
  security:
    enabled: false
    
application:
    message: Hello!
    appname: Products Backend
